//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainModel MDFSJPGVSProyectoIPSDomainModel
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("9787cc7d-2d27-4d9c-9b0b-e0845e13d017")]
	public partial class MDFSJPGVSProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// MDFSJPGVSProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x9787cc7d, 0x2d27, 0x4d9c, 0x9b, 0x0b, 0xe0, 0x84, 0x5e, 0x13, 0xd0, 0x17);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public MDFSJPGVSProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(TapizDiagramaClases),
				typeof(Clase),
				typeof(ClaseEnriquecida),
				typeof(EstiloOperacion),
				typeof(EstiloClase),
				typeof(EstiloAtributo),
				typeof(Atributo),
				typeof(Operacion),
				typeof(Parametro),
				typeof(TapizDiagramaClasesHasClases),
				typeof(ClaseEnriquecidaHasEstiloOperacioned),
				typeof(ClaseHasAtributo),
				typeof(ClaseHasOperaciones),
				typeof(Asociacion),
				typeof(AgregacionFuerte),
				typeof(AgregacionDebil),
				typeof(Herencia),
				typeof(OperacionHasParametros),
				typeof(MDFSJPGVSProyectoIPSDiagram),
				typeof(MetaforaAsociacion),
				typeof(MetaforaAgregacionFuerte),
				typeof(MetaforaAgregacionDebil),
				typeof(MetaforaHerencia),
				typeof(MetaforaClase),
				typeof(MetaforaAtributo),
				typeof(MetaforaOperacion),
				typeof(MetaforaClaseEnriquecida),
				typeof(MetaforaEstiloOperacion),
				typeof(MetaforaEstiloClase),
				typeof(MetaforaEstiloAtributo),
				typeof(MetaforaParametro),
				typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(TapizDiagramaClases), "solucionDiagramaClases", TapizDiagramaClases.solucionDiagramaClasesDomainPropertyId, typeof(TapizDiagramaClases.solucionDiagramaClasesPropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "NombreClase", Clase.NombreClaseDomainPropertyId, typeof(Clase.NombreClasePropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "NombreCompleto", Clase.NombreCompletoDomainPropertyId, typeof(Clase.NombreCompletoPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "NombreCompletoE", ClaseEnriquecida.NombreCompletoEDomainPropertyId, typeof(ClaseEnriquecida.NombreCompletoEPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "TipoLetra", EstiloOperacion.TipoLetraDomainPropertyId, typeof(EstiloOperacion.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "ColorLetra", EstiloOperacion.ColorLetraDomainPropertyId, typeof(EstiloOperacion.ColorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "EstiloOpCompleto", EstiloOperacion.EstiloOpCompletoDomainPropertyId, typeof(EstiloOperacion.EstiloOpCompletoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "Alineacion", EstiloClase.AlineacionDomainPropertyId, typeof(EstiloClase.AlineacionPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "ColorFondo", EstiloClase.ColorFondoDomainPropertyId, typeof(EstiloClase.ColorFondoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "EstiloClCompleto", EstiloClase.EstiloClCompletoDomainPropertyId, typeof(EstiloClase.EstiloClCompletoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloAtributo), "Formato", EstiloAtributo.FormatoDomainPropertyId, typeof(EstiloAtributo.FormatoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloAtributo), "EstiloAtCompleto", EstiloAtributo.EstiloAtCompletoDomainPropertyId, typeof(EstiloAtributo.EstiloAtCompletoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Nombre", Atributo.NombreDomainPropertyId, typeof(Atributo.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "TipoDato", Atributo.TipoDatoDomainPropertyId, typeof(Atributo.TipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "NameTipo", Atributo.NameTipoDomainPropertyId, typeof(Atributo.NameTipoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "TipoPrivatePublicProtected", Atributo.TipoPrivatePublicProtectedDomainPropertyId, typeof(Atributo.TipoPrivatePublicProtectedPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "Nombre", Operacion.NombreDomainPropertyId, typeof(Operacion.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "ConjuntoDatos", Operacion.ConjuntoDatosDomainPropertyId, typeof(Operacion.ConjuntoDatosPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "TipoPrivatePublicProtected", Operacion.TipoPrivatePublicProtectedDomainPropertyId, typeof(Operacion.TipoPrivatePublicProtectedPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "NameTipo", Operacion.NameTipoDomainPropertyId, typeof(Operacion.NameTipoPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "TipoDato", Operacion.TipoDatoDomainPropertyId, typeof(Operacion.TipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "TipoEntradaSalida", Parametro.TipoEntradaSalidaDomainPropertyId, typeof(Parametro.TipoEntradaSalidaPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "Nombre", Parametro.NombreDomainPropertyId, typeof(Parametro.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "TipoDatoParametro", Parametro.TipoDatoParametroDomainPropertyId, typeof(Parametro.TipoDatoParametroPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "NombreCompletoP", Parametro.NombreCompletoPDomainPropertyId, typeof(Parametro.NombreCompletoPPropertyHandler)),
				new DomainMemberInfo(typeof(Asociacion), "Nombre", Asociacion.NombreDomainPropertyId, typeof(Asociacion.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Asociacion), "CardinalidadFin", Asociacion.CardinalidadFinDomainPropertyId, typeof(Asociacion.CardinalidadFinPropertyHandler)),
				new DomainMemberInfo(typeof(Asociacion), "CardinalidadInit", Asociacion.CardinalidadInitDomainPropertyId, typeof(Asociacion.CardinalidadInitPropertyHandler)),
				new DomainMemberInfo(typeof(Herencia), "TipoHerencia", Herencia.TipoHerenciaDomainPropertyId, typeof(Herencia.TipoHerenciaPropertyHandler)),
				new DomainMemberInfo(typeof(Herencia), "TipoHijos", Herencia.TipoHijosDomainPropertyId, typeof(Herencia.TipoHijosPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizDiagramaClasesHasClases), "TapizDiagramaClases", TapizDiagramaClasesHasClases.TapizDiagramaClasesDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizDiagramaClasesHasClases), "Clase", TapizDiagramaClasesHasClases.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloOperacioned), "ClaseEnriquecida", ClaseEnriquecidaHasEstiloOperacioned.ClaseEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloOperacioned), "EstiloOperacion", ClaseEnriquecidaHasEstiloOperacioned.EstiloOperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Clase", ClaseHasAtributo.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Atributo", ClaseHasAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperaciones), "Clase", ClaseHasOperaciones.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperaciones), "Operacion", ClaseHasOperaciones.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(Asociacion), "SourceClase", Asociacion.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(Asociacion), "TargetClase", Asociacion.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(AgregacionFuerte), "SourceClase", AgregacionFuerte.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(AgregacionFuerte), "TargetClase", AgregacionFuerte.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(AgregacionDebil), "SourceClase", AgregacionDebil.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(AgregacionDebil), "TargetClase", AgregacionDebil.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(Herencia), "SourceClase", Herencia.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(Herencia), "TargetClase", Herencia.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametros), "Operacion", OperacionHasParametros.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametros), "Parametro", OperacionHasParametros.ParametroDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(22);
				createElementMap.Add(typeof(TapizDiagramaClases), 0);
				createElementMap.Add(typeof(Clase), 1);
				createElementMap.Add(typeof(ClaseEnriquecida), 2);
				createElementMap.Add(typeof(EstiloOperacion), 3);
				createElementMap.Add(typeof(EstiloClase), 4);
				createElementMap.Add(typeof(EstiloAtributo), 5);
				createElementMap.Add(typeof(Atributo), 6);
				createElementMap.Add(typeof(Operacion), 7);
				createElementMap.Add(typeof(Parametro), 8);
				createElementMap.Add(typeof(MDFSJPGVSProyectoIPSDiagram), 9);
				createElementMap.Add(typeof(MetaforaAsociacion), 10);
				createElementMap.Add(typeof(MetaforaAgregacionFuerte), 11);
				createElementMap.Add(typeof(MetaforaAgregacionDebil), 12);
				createElementMap.Add(typeof(MetaforaHerencia), 13);
				createElementMap.Add(typeof(MetaforaClase), 14);
				createElementMap.Add(typeof(MetaforaAtributo), 15);
				createElementMap.Add(typeof(MetaforaOperacion), 16);
				createElementMap.Add(typeof(MetaforaClaseEnriquecida), 17);
				createElementMap.Add(typeof(MetaforaEstiloOperacion), 18);
				createElementMap.Add(typeof(MetaforaEstiloClase), 19);
				createElementMap.Add(typeof(MetaforaEstiloAtributo), 20);
				createElementMap.Add(typeof(MetaforaParametro), 21);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new TapizDiagramaClases(partition, propertyAssignments);
				case 1: return new Clase(partition, propertyAssignments);
				case 2: return new ClaseEnriquecida(partition, propertyAssignments);
				case 3: return new EstiloOperacion(partition, propertyAssignments);
				case 4: return new EstiloClase(partition, propertyAssignments);
				case 5: return new EstiloAtributo(partition, propertyAssignments);
				case 6: return new Atributo(partition, propertyAssignments);
				case 7: return new Operacion(partition, propertyAssignments);
				case 8: return new Parametro(partition, propertyAssignments);
				case 9: return new MDFSJPGVSProyectoIPSDiagram(partition, propertyAssignments);
				case 10: return new MetaforaAsociacion(partition, propertyAssignments);
				case 11: return new MetaforaAgregacionFuerte(partition, propertyAssignments);
				case 12: return new MetaforaAgregacionDebil(partition, propertyAssignments);
				case 13: return new MetaforaHerencia(partition, propertyAssignments);
				case 14: return new MetaforaClase(partition, propertyAssignments);
				case 15: return new MetaforaAtributo(partition, propertyAssignments);
				case 16: return new MetaforaOperacion(partition, propertyAssignments);
				case 17: return new MetaforaClaseEnriquecida(partition, propertyAssignments);
				case 18: return new MetaforaEstiloOperacion(partition, propertyAssignments);
				case 19: return new MetaforaEstiloClase(partition, propertyAssignments);
				case 20: return new MetaforaEstiloAtributo(partition, propertyAssignments);
				case 21: return new MetaforaParametro(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(9);
				createElementLinkMap.Add(typeof(TapizDiagramaClasesHasClases), 0);
				createElementLinkMap.Add(typeof(ClaseEnriquecidaHasEstiloOperacioned), 1);
				createElementLinkMap.Add(typeof(ClaseHasAtributo), 2);
				createElementLinkMap.Add(typeof(ClaseHasOperaciones), 3);
				createElementLinkMap.Add(typeof(Asociacion), 4);
				createElementLinkMap.Add(typeof(AgregacionFuerte), 5);
				createElementLinkMap.Add(typeof(AgregacionDebil), 6);
				createElementLinkMap.Add(typeof(Herencia), 7);
				createElementLinkMap.Add(typeof(OperacionHasParametros), 8);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizDiagramaClasesHasClases(partition, roleAssignments, propertyAssignments);
				case 1: return new ClaseEnriquecidaHasEstiloOperacioned(partition, roleAssignments, propertyAssignments);
				case 2: return new ClaseHasAtributo(partition, roleAssignments, propertyAssignments);
				case 3: return new ClaseHasOperaciones(partition, roleAssignments, propertyAssignments);
				case 4: return new Asociacion(partition, roleAssignments, propertyAssignments);
				case 5: return new AgregacionFuerte(partition, roleAssignments, propertyAssignments);
				case 6: return new AgregacionDebil(partition, roleAssignments, propertyAssignments);
				case 7: return new Herencia(partition, roleAssignments, propertyAssignments);
				case 8: return new OperacionHasParametros(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return MDFSJPGVSProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (MDFSJPGVSProyectoIPSDomainModel.resourceManager == null)
				{
					MDFSJPGVSProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(MDFSJPGVSProyectoIPSDomainModel).Assembly);
				}
				return MDFSJPGVSProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return MDFSJPGVSProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return MDFSJPGVSProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (MDFSJPGVSProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new MDFSJPGVSProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					MDFSJPGVSProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return MDFSJPGVSProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (MDFSJPGVSProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new MDFSJPGVSProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					MDFSJPGVSProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return MDFSJPGVSProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class MDFSJPGVSProyectoIPSDeleteClosure : MDFSJPGVSProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public MDFSJPGVSProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class MDFSJPGVSProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public MDFSJPGVSProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.MDFSJPGVSProyectoIPS.TapizDiagramaClasesHasClases.ClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaHasEstiloOperacioned.EstiloOperacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.MDFSJPGVSProyectoIPS.ClaseHasAtributo.AtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.MDFSJPGVSProyectoIPS.ClaseHasOperaciones.OperacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.MDFSJPGVSProyectoIPS.OperacionHasParametros.ParametroDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class MDFSJPGVSProyectoIPSCopyClosure : MDFSJPGVSProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public MDFSJPGVSProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class MDFSJPGVSProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public MDFSJPGVSProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoLetraEnum
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoLetraEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoLetraEnum
	{
		/// <summary>
		/// Arial
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoLetraEnum.Arial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoLetraEnum/Arial.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Arial = 0,
		/// <summary>
		/// TimesNewRoman
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoLetraEnum.TimesNewRoman
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoLetraEnum/TimesNewRoman.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		TimesNewRoman = 2,
		/// <summary>
		/// Italic
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoLetraEnum.Italic
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoLetraEnum/Italic.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Italic = 1,
	}
}
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: FormatoEnum
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.FormatoEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum FormatoEnum
	{
		/// <summary>
		/// TextoNormal
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.FormatoEnum.TextoNormal
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.FormatoEnum/TextoNormal.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		TextoNormal = 0,
		/// <summary>
		/// Checkbox
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.FormatoEnum.Checkbox
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.FormatoEnum/Checkbox.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Checkbox = 1,
		/// <summary>
		/// Radiobutton
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.FormatoEnum.Radiobutton
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.FormatoEnum/Radiobutton.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Radiobutton = 2,
	}
}
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoDatoEnum
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoDatoEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoDatoEnum
	{
		/// <summary>
		/// Int
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoDatoEnum.Int
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoDatoEnum/Int.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Int = 2,
		/// <summary>
		/// Boolean
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoDatoEnum.Boolean
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoDatoEnum/Boolean.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Boolean = 0,
		/// <summary>
		/// Float
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoDatoEnum.Float
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoDatoEnum/Float.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Float = 1,
		/// <summary>
		/// String
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoDatoEnum.String
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoDatoEnum/String.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		String = 3,
	}
}
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoHerenciaPadre
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaPadre
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoHerenciaPadre
	{
		/// <summary>
		/// Total
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaPadre.Total
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaPadre/Total.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Total = 0,
		/// <summary>
		/// Parcial
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaPadre.Parcial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaPadre/Parcial.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Parcial = 1,
	}
}
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoHerenciaHijos
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaHijos
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoHerenciaHijos
	{
		/// <summary>
		/// Solapada
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaHijos.Solapada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaHijos/Solapada.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Solapada = 0,
		/// <summary>
		/// Disjunta
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaHijos.Disjunta
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoHerenciaHijos/Disjunta.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Disjunta = 1,
	}
}
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoEntradaSalidaEnum
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoEntradaSalidaEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoEntradaSalidaEnum
	{
		/// <summary>
		/// Entrada
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoEntradaSalidaEnum.Entrada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoEntradaSalidaEnum/Entrada.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Entrada = 0,
		/// <summary>
		/// Salida
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoEntradaSalidaEnum.Salida
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoEntradaSalidaEnum/Salida.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Salida = 1,
		/// <summary>
		/// EntradaySalida
		/// Description for
		/// UPM_IPS.MDFSJPGVSProyectoIPS.TipoEntradaSalidaEnum.EntradaySalida
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoEntradaSalidaEnum/EntradaySalida.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		EntradaySalida = 2,
	}
}
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoPrivatePublicProtected
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoPrivatePublicProtected
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoPrivatePublicProtected
	{
		/// <summary>
		/// Public
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoPrivatePublicProtected.Public
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoPrivatePublicProtected/Public.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Public = 0,
		/// <summary>
		/// Private
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.TipoPrivatePublicProtected.Private
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoPrivatePublicProtected/Private.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Private = 1,
		/// <summary>
		/// Protected
		/// Description for
		/// UPM_IPS.MDFSJPGVSProyectoIPS.TipoPrivatePublicProtected.Protected
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.TipoPrivatePublicProtected/Protected.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		Protected = 2,
	}
}
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: CardinalidadesEnum
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.CardinalidadesEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum CardinalidadesEnum
	{
		/// <summary>
		/// I
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.CardinalidadesEnum.I
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.CardinalidadesEnum/I.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		I = 0,
		/// <summary>
		/// N
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.CardinalidadesEnum.N
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.CardinalidadesEnum/N.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		N = 1,
	}
}
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: AlineacionEnum
	/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.AlineacionEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum AlineacionEnum
	{
		/// <summary>
		/// center
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.AlineacionEnum.center
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.AlineacionEnum/center.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		center = 0,
		/// <summary>
		/// left
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.AlineacionEnum.left
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.AlineacionEnum/left.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		left = 1,
		/// <summary>
		/// right
		/// Description for UPM_IPS.MDFSJPGVSProyectoIPS.AlineacionEnum.right
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.MDFSJPGVSProyectoIPS.AlineacionEnum/right.Description", typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel), "UPM_IPS.MDFSJPGVSProyectoIPS.GeneratedCode.DomainModelResx")]
		right = 2,
	}
}

