//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class MDFSJPGVSProyectoIPSToolboxHelper : MDFSJPGVSProyectoIPSToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new MDFSJPGVSProyectoIPSToolboxHelper.
		/// </summary>
		public MDFSJPGVSProyectoIPSToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class MDFSJPGVSProyectoIPSToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify MDFSJPGVSProyectoIPS toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "MDFSJPGVSProyectoIPS.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify HerenciaTool connector tool.
		/// </summary>
		public const string HerenciaToolFilterString = "HerenciaTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify AsociacionTool connector tool.
		/// </summary>
		public const string AsociacionToolFilterString = "AsociacionTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify AgregacionDebil connector tool.
		/// </summary>
		public const string AgregacionDebilFilterString = "AgregacionDebil.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify AgregacionFuerteTool connector tool.
		/// </summary>
		public const string AgregacionFuerteToolFilterString = "AgregacionFuerteTool.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new MDFSJPGVSProyectoIPSToolboxHelperBase.
		/// </summary>
		protected MDFSJPGVSProyectoIPSToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel.SingletonResourceManager.GetString("ClaseToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 4;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolToolboxItem":
					// Add ClaseTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ClaseToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ClaseToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ClaseTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ClaseToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.Clase.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.AtributoClaseToolToolboxItem":
					// Add AtributoClaseTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.AtributoClaseToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AtributoClaseToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AtributoClaseToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AtributoClaseTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AtributoClaseToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.Atributo.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.OperacionClaseToolToolboxItem":
					// Add OperacionClaseTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.OperacionClaseToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("OperacionClaseToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OperacionClaseToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"OperacionClaseTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("OperacionClaseToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.Operacion.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.ParametroOperacionToolToolboxItem":
					// Add ParametroOperacionTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.ParametroOperacionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ParametroOperacionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ParametroOperacionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ParametroOperacionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ParametroOperacionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.Parametro.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.HerenciaToolToolboxItem":

					// Add HerenciaTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.HerenciaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("HerenciaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HerenciaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.MDFSJPGVSProyectoIPS.RelacionesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("RelacionesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"HerenciaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("HerenciaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(HerenciaToolFilterString)
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.AsociacionToolToolboxItem":

					// Add AsociacionTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.AsociacionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AsociacionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AsociacionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.MDFSJPGVSProyectoIPS.RelacionesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("RelacionesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AsociacionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AsociacionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(AsociacionToolFilterString)
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.AgregacionDebilToolboxItem":

					// Add AgregacionDebil connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.AgregacionDebilToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AgregacionDebilToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AgregacionDebilToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.MDFSJPGVSProyectoIPS.RelacionesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("RelacionesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AgregacionDebil", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AgregacionDebilToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(AgregacionDebilFilterString)
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.AgregacionFuerteToolToolboxItem":

					// Add AgregacionFuerteTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.AgregacionFuerteToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AgregacionFuerteToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AgregacionFuerteToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.MDFSJPGVSProyectoIPS.RelacionesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("RelacionesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AgregacionFuerteTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AgregacionFuerteToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(AgregacionFuerteToolFilterString)
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolToolboxItem":
					// Add ClaseEnriquecidaTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ClaseEnriquecidaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ClaseEnriquecidaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseEnriquecidaToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ClaseEnriquecidaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ClaseEnriquecidaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecida.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.EstiloOperacionToolToolboxItem":
					// Add EstiloOperacionTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.EstiloOperacionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EstiloOperacionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EstiloOperacionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseEnriquecidaToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EstiloOperacionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EstiloOperacionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.EstiloOperacion.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.EstiloClaseToolToolboxItem":
					// Add EstiloClaseTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.EstiloClaseToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EstiloClaseToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EstiloClaseToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseEnriquecidaToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EstiloClaseTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EstiloClaseToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.EstiloClase.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.EstiloAtributoToolToolboxItem":
					// Add EstiloAtributoTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.EstiloAtributoToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EstiloAtributoToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EstiloAtributoToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseEnriquecidaToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EstiloAtributoTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EstiloAtributoToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.EstiloAtributo.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.AtributoClaseEnriquecidaToolToolboxItem":
					// Add AtributoClaseEnriquecidaTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.AtributoClaseEnriquecidaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AtributoClaseEnriquecidaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AtributoClaseEnriquecidaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseEnriquecidaToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AtributoClaseEnriquecidaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AtributoClaseEnriquecidaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.Atributo.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.OperacionClaseEnriquecidaToolToolboxItem":
					// Add OperacionClaseEnriquecidaTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.OperacionClaseEnriquecidaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("OperacionClaseEnriquecidaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OperacionClaseEnriquecidaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseEnriquecidaToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"OperacionClaseEnriquecidaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("OperacionClaseEnriquecidaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.Operacion.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.MDFSJPGVSProyectoIPS.ParametroOperacionCEToolToolboxItem":
					// Add ParametroOperacionCETool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.MDFSJPGVSProyectoIPS.ParametroOperacionCEToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ParametroOperacionCEToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ParametroOperacionCEToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ClaseEnriquecidaToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ParametroOperacionCETool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ParametroOperacionCEToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.MDFSJPGVSProyectoIPS.Parametro.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
