//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "MDFSJPGVSProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MDFSJPGVSProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MDFSJPGVSProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MDFSJPGVSProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MDFSJPGVSProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MDFSJPGVSProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMDFSJPGVSProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MDFSJPGVSProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string MDFSJPGVSProyectoIPSPackageId = "a58a905c-88c3-4630-9474-5ef601f2dd1a";
		
		// Editor factory identifier
		public const string MDFSJPGVSProyectoIPSEditorFactoryId = "2536aa88-3345-49c3-8118-630f44d2c34e";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MDFSJPGVSProyectoIPSModelExplorerToolWindowId = "f8661d83-2704-4056-a1a5-3f5a49d4b85c";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MDFSJPGVSProyectoIPSCommandSetId = "4a7ef3de-b954-45c8-a82c-5ab375aec9d0";
	}
}