//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;

namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
	[VSShell::ProvideToolWindow(typeof(MDFSJPGVSProyectoIPSExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(MDFSJPGVSProyectoIPSExplorerToolWindow), Constants.MDFSJPGVSProyectoIPSEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@ClaseToolboxTab;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", "UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolboxTab",
					"@ClaseToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ClaseTool", 
					"@ClaseToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolboxTab",
					"@AtributoClaseToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.AtributoClaseToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoClaseTool", 
					"@AtributoClaseToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolboxTab",
					"@OperacionClaseToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.OperacionClaseToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"OperacionClaseTool", 
					"@OperacionClaseToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseToolboxTab",
					"@ParametroOperacionToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.ParametroOperacionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ParametroOperacionTool", 
					"@ParametroOperacionToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxGroup("@RelacionesToolboxTab;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", "UPM_IPS.MDFSJPGVSProyectoIPS.RelacionesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.RelacionesToolboxTab",
					"@HerenciaToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.HerenciaToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"HerenciaTool", 
					"@HerenciaToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.RelacionesToolboxTab",
					"@AsociacionToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.AsociacionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AsociacionTool", 
					"@AsociacionToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.RelacionesToolboxTab",
					"@AgregacionDebilToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.AgregacionDebilToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AgregacionDebil", 
					"@AgregacionDebilToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.RelacionesToolboxTab",
					"@AgregacionFuerteToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.AgregacionFuerteToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AgregacionFuerteTool", 
					"@AgregacionFuerteToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxGroup("@ClaseEnriquecidaToolboxTab;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", "UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab",
					"@ClaseEnriquecidaToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ClaseEnriquecidaTool", 
					"@ClaseEnriquecidaToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab",
					"@EstiloOperacionToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.EstiloOperacionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EstiloOperacionTool", 
					"@EstiloOperacionToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab",
					"@EstiloClaseToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.EstiloClaseToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EstiloClaseTool", 
					"@EstiloClaseToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab",
					"@EstiloAtributoToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.EstiloAtributoToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EstiloAtributoTool", 
					"@EstiloAtributoToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab",
					"@AtributoClaseEnriquecidaToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.AtributoClaseEnriquecidaToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoClaseEnriquecidaTool", 
					"@AtributoClaseEnriquecidaToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab",
					"@OperacionClaseEnriquecidaToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.OperacionClaseEnriquecidaToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"OperacionClaseEnriquecidaTool", 
					"@OperacionClaseEnriquecidaToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.MDFSJPGVSProyectoIPS.ClaseEnriquecidaToolboxTab",
					"@ParametroOperacionCEToolToolboxItem;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					"UPM_IPS.MDFSJPGVSProyectoIPS.ParametroOperacionCEToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ParametroOperacionCETool", 
					"@ParametroOperacionCEToolToolboxBitmap;UPM_IPS.MDFSJPGVSProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 14)]
	[VSShell::ProvideEditorFactory(typeof(MDFSJPGVSProyectoIPSEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(MDFSJPGVSProyectoIPSEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(MDFSJPGVSProyectoIPSEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"MDFSJPGVSProyectoIPS", typeof(MDFSJPGVSProyectoIPSEditorFactory))]

	internal abstract partial class MDFSJPGVSProyectoIPSPackageBase : DslShell::AsyncModelingPackage
	{
		protected global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected async override Task InitializeAsync(CancellationToken cancellationToken, IProgress<VSShell.ServiceProgressData> progress)
		{
			await base.InitializeAsync(cancellationToken, progress);

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new MDFSJPGVSProyectoIPSEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			MDFSJPGVSProyectoIPSCommandSet commandSet = new MDFSJPGVSProyectoIPSCommandSet(this);
			await commandSet.InitializeAsync(cancellationToken);
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			MDFSJPGVSProyectoIPSClipboardCommandSet clipboardCommandSet = new MDFSJPGVSProyectoIPSClipboardCommandSet(this);
			await clipboardCommandSet.InitializeAsync(cancellationToken);
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(MDFSJPGVSProyectoIPSExplorerToolWindow));

			if (cancellationToken.IsCancellationRequested)
			{
				return;
			}

			await JoinableTaskFactory.SwitchToMainThreadAsync();

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			await this.SetupDynamicToolboxAsync(cancellationToken);
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch (global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}

		public override VSShellInterop::IVsAsyncToolWindowFactory GetAsyncToolWindowFactory(Guid toolWindowType)
		{
			if (toolWindowType == typeof(MDFSJPGVSProyectoIPSExplorerToolWindow).GUID)
			{
				return this;
			}

			return base.GetAsyncToolWindowFactory(toolWindowType);
		}
	}
}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace UPM_IPS.MDFSJPGVSProyectoIPS
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDirectiveProcessor), global::UPM_IPS.MDFSJPGVSProyectoIPS.MDFSJPGVSProyectoIPSDirectiveProcessor.MDFSJPGVSProyectoIPSDirectiveProcessorName, "A directive processor that provides access to MDFSJPGVSProyectoIPS files")]
	[global::System.Runtime.InteropServices.Guid(Constants.MDFSJPGVSProyectoIPSPackageId)]
	internal sealed partial class MDFSJPGVSProyectoIPSPackage : MDFSJPGVSProyectoIPSPackageBase
	{
	}
}